export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_ADVERTS = 'GET_ADVERTS';
export const GET_ADVERTS_REQUEST = 'GET_ADVERTS_REQUEST';
export const GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS';
export const GET_ADVERTS_FAILURE = 'GET_ADVERTS_FAILURE';

export const LAYOUT_TOGGLE_LOGIN = 'LAYOUT_TOGGLE_LOGIN';
export const LAYOUT_TOGGLE_REGISTER = 'LAYOUT_TOGGLE_REGISTER';
export const LAYOUT_SWITCH_LOGIN = 'LAYOUT_SWITCH_LOGIN';
export const LAYOUT_SWITCH_REGISTER = 'LAYOUT_SWITCH_REGISTER';
export const LAYOUT_SET_SNACKBAR_INFO = 'LAYOUT_SET_SNACKBAR_INFO';
