export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const REGISTER = 'REGISTER';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';


export const LOGOUT = 'LOGOUT';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const GET_ADVERTS = 'GET_ADVERTS';
export const GET_ADVERTS_REQUEST = 'GET_ADVERTS_REQUEST';
export const GET_ADVERTS_SUCCESS = 'GET_ADVERTS_SUCCESS';
export const GET_ADVERTS_FAILURE = 'GET_ADVERTS_FAILURE';

export const CONFIRM_DELETE_ADVERT = 'CONFIRM_DELETE_ADVERT';

export const ADD_ADVERT = 'ADD_ADVERT';
export const ADD_ADVERT_REQUEST = 'ADD_ADVERT_REQUEST';
export const ADD_ADVERT_SUCCESS = 'ADD_ADVERT_SUCCESS';
export const ADD_ADVERT_FAILURE = 'ADD_ADVERT_FAILURE';

export const REMOVE_ADVERT = 'REMOVE_ADVERT';
export const REMOVE_ADVERT_REQUEST = 'REMOVE_ADVERT_REQUEST';
export const REMOVE_ADVERT_SUCCESS = 'REMOVE_ADVERT_SUCCESS';
export const REMOVE_ADVERT_FAILURE = 'REMOVE_ADVERT_FAILURE';

export const TOGGLE_ADVERT_DIALOG = 'ADVERT_TOGGLE_DIALOG';

export const ADVERTS_SEARCH_QUERY = 'ADVERTS_SEARCH_QUERY';


export const LAYOUT_TOGGLE_LOGIN = 'LAYOUT_TOGGLE_LOGIN';
export const LAYOUT_TOGGLE_REGISTER = 'LAYOUT_TOGGLE_REGISTER';
export const LAYOUT_SWITCH_LOGIN = 'LAYOUT_SWITCH_LOGIN';
export const LAYOUT_SWITCH_REGISTER = 'LAYOUT_SWITCH_REGISTER';
export const LAYOUT_SET_SNACKBAR_INFO = 'LAYOUT_SET_SNACKBAR_INFO';


export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';